### ISSUE TITLE
Leak de informatii confidentiale 

### ISSUE THREAD

**Issue by CristiVlad25** [CatalinDumitrascu/ProiectMPS#1]
Salut, vezi ca fisierul https://github.com/CatalinDumitrascu/ProiectMPS/blob/master/JuryDuty/src/res/Firebase.tsx 
e vizibil de catre public si contine informatii care (banuiesc) ca nu ar trebui sa fie vizibile de catre toata lumea, precum API keys.

**Comment by bianca-voinea** [comment]
Yep, o sa-l distribui in privat . Merci !
